#!/bin/bash

echo -e "\n*** Testing Symbol Table Output ***"

./symbol-main test/symbol/st-in-simple-declarators test/symbol/st-output
diff test/symbol/st-exp-simple-declarators test/symbol/st-output

if [ $? -eq 0 ]
then
    echo "PASS: SIMPLE DECLARATORS"
else
    echo " FAIL: SIMPLE DECLARATORS"
fi


./symbol-main test/symbol/st-in-array-declarators test/symbol/st-output
diff test/symbol/st-exp-array-declarators test/symbol/st-output

if [ $? -eq 0 ]
then
    echo "PASS: ARRAY DECLARATORS"
else
    echo " FAIL: ARRAY DECLARATORS"
fi


./symbol-main test/symbol/st-in-function-declarators test/symbol/st-output
diff test/symbol/st-exp-function-declarators test/symbol/st-output

if [ $? -eq 0 ]
then
    echo "PASS: FUNCTION DECLARATORS"
else
    echo " FAIL: FUNCTION DECLARATORS"
fi

./symbol-main test/symbol/st-in-function-definitions test/symbol/st-output
diff test/symbol/st-exp-function-definitions test/symbol/st-output

if [ $? -eq 0 ]
then
    echo "PASS: FUNCTION DEFINITIONS"
else
    echo " FAIL: FUNCTION DEFINITIONS"
fi

./symbol-main test/symbol/st-in-identifiers test/symbol/st-output
diff test/symbol/st-exp-identifiers test/symbol/st-output

if [ $? -eq 0 ]
then
    echo "PASS: IDENTIFIERS"
else
    echo " FAIL: IDENTIFIERS"
fi

echo -e "\n"