#!/bin/bash

./symbol-main test/symbol/st-in-array-declarators test/symbol/st-output
diff test/symbol/st-exp-array-declarators test/symbol/st-output

if [ $? -eq 0 ]
then
    echo "PASS: ARRAY DECLARATORS"
else
    echo " FAIL: ARRAY DECLARATORS"
fi
